#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_TOUCHKEY_BLN) += cypress-touchkey.o issp_driver_routines.o issp_main.o issp_routines.o
obj-$(CONFIG_TARGET_CM_KERNEL) += cypress-touchkey-aosp.o issp_driver_routines.o issp_main.o issp_routines.o
