#!/sbin/busybox sh
cd /
mkdir /dev/block
mknod /dev/block/mmcblk0p9 b 259 1
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system

if [ -f /system/framework/kafdex.jar ]; then
	touch /system/framework/kafdex.jar
fi;

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

if [ -f /system/recovery.cpio.gz ]; then
	mount -o remount,rw /
	zcat /system/recovery.cpio.gz | cpio -idmu
fi;

MIUI=0

[ "`/sbin/busybox grep -i =MIUI /system/build.prop`" ] && MIUI=1
[ -f /system/framework/framekwork-miui-res.apk ] && MIUI=1

if [ "$MIUI" == 1 ]; then
	mv -f /init.miui /init.rc
fi;

rm -f /init.miui
busybox umount /system
exec /sbin/init.cm
