#!/sbin/busybox sh
cd /
mkdir /dev/block
mknod /dev/block/mmcblk0p9 b 259 1
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

if [ -f /system/recovery.cpio.gz ]; then
	mount -o remount,rw /
	zcat /system/recovery.cpio.gz | cpio -idmu
fi;

if [ ! -d /system/lib/modules ]; then
	mount -o remount,rw /system
	mkdir /system/lib/modules
fi;

cp -f /lib/modules/* /system/lib/modules

busybox umount /system
exec /sbin/init.cm
